---
kind: Service
apiVersion: v1
metadata:
  name: post-service
spec:
  selector:
     # Should match the template.metadata.labels.app value
    app: post
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 7112
      # Port accessible outside cluster
      nodePort: 30005
      name: http
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  selector:
    matchLabels:
        app: post
  replicas: 1
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: prashantdocker87/post:one
          #same port as mentioned in applciations application.properties
          ports:
            - containerPort: 7112
          