---
kind: Service
apiVersion: v1
metadata:
  name: blog-service
spec:
  selector:
     # Should match the template.metadata.labels.app value
    app: blog
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 7111
      # Port accessible outside cluster
      nodePort: 30004
      name: http
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
spec:
  selector:
    matchLabels:
        app: blog
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: prashantdocker87/blog:one
          #same port as mentioned in applciations application.properties
          ports:
            - containerPort: 7111
          